language: ruby
rvm:
- 2.3.1
cache: bundler
before_script:
- psql -c 'create database cbcv_test_database' -U postgres
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
  - bundle exec rake code_analysis
services:
- postgresql
addons:
  postgresql: '9.4'
