default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
 <<: *default
 database: library_api_database

test:
 <<: *default
 database: library_test_database

production:
  url: <%= ENV['DATABASE_URL'] %>
